# Travis CI Configuration File

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Tell Travis CI we're using PHP
language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - WP_VERSION=master
    - WP_VERSION=4.1
    - WP_VERSION=4.0
    - WP_VERSION=3.9
    - WP_VERSION=3.8

matrix:
  fast_finish: true
  include:
    - php: 5.2
      env: WP_VERSION=master
    - php: hhvm
      env: WP_VERSION=master
    - php: nightly
      env: WP_VERSION=master
  allow_failures:
    - php: hhvm
    - php: nightly

# Clones WordPress and configures our testing environment.
before_script:
    - bash bin/install-wp-tests-travis.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
